Repository cassiofb-dev/weather-visualization-tool, pull requests merged in 2022-06, with the labels that each got.

#41 Fix readme mobile ux
  README.md
  frontend/src/app/routes/about/about.component.html
  frontend/src/app/routes/docs/docs.component.html
Labels: documentation

#42 bugfix: enviroments urls
  README.md
Labels: bugfix

#43 Estações pluviométricas e plot da variável lightening
  frontend/angular.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.scss
  frontend/src/app/app.module.ts
  frontend/src/app/routes/home/home.component.html
  frontend/src/app/routes/home/home.component.ts
  frontend/src/app/routes/home/home.service.ts
  frontend/src/assets/data/dados_.json
  frontend/src/assets/data/rj.json
  frontend/src/assets/images/layers-2x.png
  frontend/src/assets/images/layers.png
  frontend/src/assets/images/marker-icon-2x.png
  frontend/src/assets/images/marker-icon.png
  frontend/src/assets/images/marker-shadow.png
Labels: priority, feature
